### ISSUE TITLE
Display issues when scrolling in the minibuffer frame

### ISSUE THREAD

**Issue by clemera** [honmaple/emacs-maple-minibuffer#1]
This looks really interesting, thanks for creating this. I have been using `ivy-posframe` before but I like that your approach is more general and works for any minibuffer prompt. The code is simpler, too, which is nice. I have one problem that when I move down in the minibuffer frame to the point where it's scrolls I get some display issues. See the screenshot:

![pixel](https://user-images.githubusercontent.com/13802849/62969952-ae069f80-be0e-11e9-8200-5be65a5fa2c0.png)
 

Any ideas what's the issue? 

I'm using Emacs 26.1.

**Comment by honmaple** [comment]
```
;; init-test.el

(setq package-enable-at-startup nil
      package--init-file-ensured t)

(package-initialize)

(require 'ivy)
(ivy-mode 1)

(require 'maple-minibuffer)
(maple-minibuffer-mode 1)
```
Use `emacs --load init-test.el -Q` test it again

**Comment by clemera** [comment]
After several attempts I finally found how I can reproduce it. I doesn't happen when I keep the initial frame size Emacs starts with. But if I maximize the frame and afterwards use the minibuffer, it happens. Here is the code which can reproduce it:


    (package-initialize)

    (require 'ivy)
    (ivy-mode 1)

    (require 'maple-minibuffer)
    (maple-minibuffer-mode 1)



    (toggle-frame-maximized)

    ;; for some reasone this need to wait a bit for
    ;; the effect to appear
    (run-at-time 1 nil #'counsel-M-x)

After loading the above and scrolling down the  candidate list with `C-n` the display issues appear.

**Comment by honmaple** [comment]
Well, I still can't reproduce it in ArchLinux and MacOS. What system are you using? Or please change `maple-minibuffer:position-type` and test it again.

**Comment by clemera** [comment]
Yeah, it's strange. I'm on Ubuntu using Gnome DE. I changed the position type but it does not help. I will investigate a bit and report back when I find something. Thank you!

**Comment by clemera** [comment]
I found a fix: Adding `(inhibit-double-buffering . t)` to the frame paramters via `maple-minibuffer:parameters` fixed it for me. The manual mentions this setting can influence display bugs.
