### ISSUE TITLE
minibuffer opens in the wrong frame 

### ISSUE THREAD

**Issue by ashfaqfarooqui** [honmaple/emacs-maple-minibuffer#6]
I use a multi-monitor setup with i3 as my WM. I have Emacs run as a demon and I usually have several clients running. 

When I open the mini-buffer it always opens with (usually, not always) the first emacs client that was spawned. And, it rarely respects the monitor on which it is called.

I'm not really sure what I can help you with here, logs? config? Do let me know if you need any more inputs from my end.

**Comment by honmaple** [comment]
Sorry for late reply,`maple-minibuffer` would be created  as child frame of current frame, and cache it to speed up the display of `minibuffer frame`,  If you want to open another frame, you should disable `maple-minibuffer:cache` by
```
(setq maple-minibuffer:cache nil)
```

**Comment by ashfaqfarooqui** [comment]
Thanks! I did not know that!

It works perfectly now :)
